this = player;

removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;
this forceAddUniform "ARC_GER_flecktarn_Uniform";
this addItemToUniform "ACE_MapTools";
this addItemToUniform "ACE_DefusalKit";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_CableTie";};
this addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 8 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 4 do {this addItemToUniform "ACE_morphine";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_epinephrine";};
this addItemToUniform "ACE_bloodIV_500";
this addItemToUniform "16Rnd_9x21_Mag";
this addVest "ARC_GER_flecktarn_Plate_Carrier";
for "_i" from 1 to 2 do {this addItemToVest "rhs_200rnd_556x45_M_SAW";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addBackpack "ARC_GER_Backpack_compact_flecktarn";
this addItemToBackpack "rhs_200rnd_556x45_M_SAW";
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
this addItemToBackpack "SmokeShellBlue";
this addItemToBackpack "SmokeShellRed";
this addHeadgear "ARC_GER_flecktarn_Mich";
this addWeapon "rhs_weap_m249_pip_S_vfg";
this addPrimaryWeaponItem "FHQ_optic_HWS_G33";
this addWeapon "hgun_P07_F";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "tf_anprc152";